name: education_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  shared_preferences: ^2.3.1
  injectable: ^2.4.4
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  intl: ^0.19.0
  flutter_web_frame: ^1.0.0
  auto_route: ^9.1.0
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.4.0
  audioplayers: ^6.0.0
  video_player: ^2.9.1
  chewie: ^1.8.2
  carousel_slider: ^4.2.1
  flutter_easyrefresh: ^2.2.2
  freezed_annotation: ^2.4.4
  hive_flutter: ^1.1.0
  stream_transform: ^2.1.0
  hive: ^2.0.4
  get_it: ^7.2.0
  event_bus: ^2.0.0
  card_swiper: ^3.0.1
  fluro: ^2.0.5
  hms_room_kit: ^1.1.5
  hmssdk_flutter: ^1.10.5
  permission_handler: ^11.3.1
  tapped: ^2.0.0
  flutter_spinkit: ^5.2.1
  safemap: ^2.1.0
  azlistview: ^2.0.0
  extended_text_field: ^15.0.0
  flutter_keyboard_visibility: ^6.0.0
  lpinyin: ^2.0.3
  extended_nested_scroll_view: ^6.2.1
  fluttertoast: ^8.2.6
  wakelock_web: ^0.4.0
  flutter_riverpod: ^2.5.1
  sembast: ^3.7.2
  logman: ^0.0.20
  flutter_pdfview: ^1.3.2
  graphic: ^2.4.0
  quiver: ^3.2.1
  fl_chart: ^0.68.0
  oktoast: ^3.4.0
  process_run: ^1.1.0
  universal_platform: ^1.1.0

  sp_util: 2.0.3
  common_utils: 2.1.0

  geolocator: ^12.0.0
  flutter_floating: ^1.0.8
  flutter_chat_types: ^3.6.2




dev_dependencies:
  flutter_test:
    sdk: flutter
    # build_runner: ^2.4.11
    # injectable_generator: ^2.6.2
    # hive_generator: ^2.0.1
    # flutter_lints: ^3.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      
      - assets/images/live/
      - assets/images/xuanze/
      - assets/xiyouji/
      - assets/xiyouji/sound/
      - assets/video/oneclassenglishdown/
      - assets/video/oneclassEnglishup/
      - assets/video/oneclassmathdown/
      - assets/video/oneclassmathup/
      - assets/video/twochinese/chinese1.mp4
      - assets/video/twochinese/chinese1.mp4
      - assets/video/twochinese/chinese2.mp4
      - assets/video/twochinese/chinese3.mp4
      - assets/video/twochinese/
      - assets/video/twomath/
      - assets/video/
      - assets/video/jishi/
      - assets/video/class/

      - assets/images/pk/
      - assets/images/yuanshen/
      - assets/images/statistic/
      - assets/lottie/
   
      - assets/images/
      - assets/images/myhome/
      - assets/images/course/math/
      - assets/images/course/english/
      - assets/images/course/chinese/
      - assets/images/xiyouji/
      - assets/images/3.0x/
      - assets/images/retangle/
      - assets/images/2.0x/
      - assets/icons/
     
      - assets/xiyouji/
      - assets/images/banner1.png
      - assets/images/banner2.png
      - assets/images/banner.png
      - assets/images/Rectangle 3.png
      - assets/images/Rectangle 4.png
      - assets/images/短视频.png
      - assets/images/奖牌.png
      - assets/images/举手.png
      - assets/images/学习.png
      - assets/images/动图.gif
      - assets/images/直播1.jpg
      - assets/images/直播2.jpg
      - assets/images/直播3.jpg
      - assets/images/直播4.jpg
      - assets/images/直播5.jpg
      - assets/images/好好学习.jpg
      - assets/images/直播6.jpg
      - assets/images/直播7.jpg
      - assets/images/c1.jpg
      - assets/images/c2.jpg
      - assets/images/c3.jpg
     
      - assets/images/英语2.jpg
      - assets/images/英语1.jpg
      - assets/images/英语3.jpg
      - assets/images/TainCamp.jpg
      - assets/images/TainCamp1.jpg
      - assets/images/TainCamp2.jpg
      
      - assets/images/TainCampCopy1.jpg
      - assets/images/TainCampCopy2.jpg
      - assets/images/TainCampCopy3.jpg
      - assets/images/3.0x/1.jpg
      - assets/icons/福利.png
      - assets/icons/一对一.png
      - assets/icons/live.png
      - assets/icons/moreclass.png
      - assets/icons/video.png
      - assets/images/tiger.gif
      - assets/images/认知训练营.png
      - assets/images/草原.jpg
      - assets/images/fox.gif
      - assets/images/chicken.gif
      - assets/images/lion.gif
      - assets/images/elephant.gif
      - assets/images/bird.gif
      - assets/images/zoo1.jpg
      - assets/images/zoo.png 
      - assets/images/迷宫.jpg
      - assets/images/livesocket.jpg


      - assets/images/3.0x/woshishui.jpg
      - assets/images/3.0x/pk.jpg
      - assets/images/3.0x/migong.jpg
      - assets/images/retangle/14retangle.png
      - assets/images/retangle/24retangle.png
      - assets/images/retangle/34retangle.png
      - assets/images/retangle/44retangle.png
      - assets/images/xiyouji/xiyouji1.jpg
      - assets/images/xiyouji/xiyouji2.jpg
      - assets/images/xiyouji/xiyouji3.jpg
      - assets/images/xiyouji/xiyouji4.jpg
      - assets/images/xiyouji/xiyouji5.jpg

      - assets/sounds/chicken.mp3
      - assets/sounds/elephant.mp3
      - assets/sounds/lion.mp3
      - assets/sounds/lazysheep1.wav
      - assets/sounds/lazysheep2.wav
      - assets/sounds/lazysheepdunmabu.wav
      - assets/sounds/lazysheepfood.wav
      - assets/sounds/lazysheepfood2.wav
      - assets/sounds/lazysheepfood2.wav
      - assets/sounds/lazysheeppoem.wav
      - assets/sounds/lazysheepshendun.wav
      - assets/sounds/zhuanpan.mp3
      - assets/xiyouji/sound/missah.wav
      - assets/xiyouji/sound/missun.wav
      - assets/xiyouji/sound/mistang.wav
      - assets/xiyouji/sound/miszhu.wav



      - assets/images/animals.jpg
      - assets/images/3.0x/课前1.jpg
      - assets/images/3.0x/课前2.jpg
      - assets/images/3.0x/课前3.jpg
      - assets/images/3.0x/课前4.jpg
      - assets/images/3.0x/课前5.jpg
      - assets/images/3.0x/blindbox.jpg
      - assets/images/3.0x/blindbox.png
      - assets/images/blindbox.gif
      - assets/images/blindbox1.png
      - assets/images/blindbox2.png
      - assets/images/blindbox3.png
      - assets/images/lazysheep.jpg
      - assets/images/lazysheep1.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
